routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\ArticleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [AuthController::class, 'index'])->name('welcome');
Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('post-login', [AuthController::class, 'postLogin'])->name('login.post'); 
Route::get('registration', [AuthController::class, 'registration'])->name('register');
Route::post('post-registration', [AuthController::class, 'postRegistration'])->name('register.post'); 
Route::get('dashboard', [AuthController::class, 'dashboard']); 
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::resource('article', ArticleController::class);

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'header', 'body', 'footer', 'image_url', 'tag', 'slug', 'writer'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Article;
use Validator;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use Illuminate\Support\Facades\Storage;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::all();
        return view('article.index', compact('articles'));
    }
    
    public function show($slug)
    {
        $articles = Article::all();
        // $articles = Article::where('slug', 'LIKE', '%'.$slug.'%')->first();
        return view('article.read', compact('articles'));
    }

    public function create()
    {
        return view('article.create');
    }

    public function store(Request $request){
        $validator = Validator::make($request->all(),[
                                    'title' => ['required'],
                                    'header' => ['required'],
                                    'body' => ['required'],
                                    'footer' => ['required'],
                                    'tag' => ['required'],
                                    'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                    ]);
                    
        if($validator->fails()){
            return back()->with('error', 'Ada Beberapa form yang terlewat');
        }

        $title = $request->title;
        $header = $request->header;
        $body = $request->body;
        $footer = $request->footer;
        $tag = $request->tag;
        $slug = $this->slugify($title);

        $article_selected = Article::where('slug', $slug)->first();
        if($article_selected){
            return back()->with('error', 'Sudah ada artikel dengan slug yang sama');
            die();
        }

        $imageName = $request->image->getClientOriginalName();               
        $request->image->move(public_path('images/artikel'), $imageName);
        
        $user = User::find(1);

        $article_new = new Article;
        $article_new->title = $title;
        $article_new->header = $header;
        $article_new->body = $body;
        $article_new->footer = $footer;
        $article_new->tag = $tag;
        $article_new->slug = $slug;
        $article_new->writer = $user->name;
        $article_new->image_url = $imageName;
        $article_new->save();
        return redirect()->route('article.index')->with('success', 'Artikel berhasil terbuat');
    }
    public function edit($id)
    {
        $article = Article::findOrFail($id);

        return view('article.edit', [
            'article' => $article
        ]);
    }
    public function update(Request $request, $id)
    {
        $article = Article::find($id)->update($request->all());
        
        $article = Article::where('id',$id)->first();
        unlink('images/artikel/'.$article['image_url']);
        
        // $image = $request->file('image');
        // $imageName = $image->getClientOriginalName();
        // $image->move(public_path('images/artikel'), $imageName);

        $imageName = $request->image->getClientOriginalName();               
        $request->image->move(public_path('images/artikel'), $imageName);

        $article->image_url = $imageName;
        $article->save();

        return redirect()->route('article.index')->with('success',' Data telah diperbaharui!');
    }

    public function destroy(Request $request, $id)
    {
        $article_selected = Article::find($id);
        $article_selected->delete();
        return redirect()->route('article.index')->with('success', 'Artikel berhasil terhapus');
    }

    private function slugify ($string) {
        $string = utf8_encode($string);
        $string = iconv('UTF-8', 'ASCII//TRANSLIT', $string);   
        $string = preg_replace('/[^a-z0-9- ]/i', '', $string);
        $string = str_replace(' ', '-', $string);
        $string = trim($string, '-');
        $string = strtolower($string);
    
        if (empty($string)) {
            return 'n-a';
        }
    
        return $string;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/article/create.blade.php
@extends('layout')
@section('title')
    Artikel
@endsection
@section('style')
    <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
@endsection
@section('content')

        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-outline card-info">
              <div class="card-header">
                <h3 class="card-title">
                  Buat Artikel Baru Disini
                  <small>Simple Article Editor</small>
                </h3>
                <!-- tools box -->
                <div class="card-tools">
                    {{--  --}}
                </div>
                <!-- /. tools -->
              </div>
              <!-- /.card-header -->
                <form action="{{ route('article.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body pad">
                        <div class="form-group">
                          <label class="form-label">Title</label>
                          <input type="text" name="title" class="form-control" placeholder="Tuliskan title artikel" required/>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Header</label>
                            <input type="text" name="header" class="form-control" placeholder="Tuliskan header tambahan" required/>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Image Upload</label>
                            <input type="file" name="image" class="form-control" required>
                        </div>
                        <div class="my-3">
                            <label class="form-label">Body</label>
                            <textarea name="body" class="textarea" placeholder="Place some text here"
                            style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Footer</label>
                            <input type="text" name="footer" class="form-control" placeholder="Tuliskan footer tambahan" required/>
                        </div>
                        <div class="form-group row">
                          <div class="col">
                            <label class="form-label">Tag</label>
                            <input type="text" name="tag" class="form-control" placeholder="Tuliskan topik yang berkaitan dengan hal ini (ex: kerja, menarik, fulltime, tips) ..."  required/>
                          </div>
                        </div>
                        <p class="text-sm mb-0">
                            Editor <a href="https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg">Documentation and license
                            information.</a>
                        </p>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary w-100">Simpan Artikel</button>
                    </div>
                </form>
            </div>
          </div>
          <!-- /.col-->
        </div>
        <!-- ./row -->
      </section>
</div>
@endsection
@section('script')
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<script>
  $(function () {
    $('.textarea').summernote()
  })
</script>
@endsection

resources/views/article/edit.blade.php
@extends('layout')

@section('title')
    Artikel
@endsection
@section('style')
    <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
@endsection
@section('content')
<div class="content-wrapper">

        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-outline card-info">
              <div class="card-header">
                <h3 class="card-title">
                  Edit Artikel Disini
                  <small>Simple Article Editor</small>
                </h3>
                <!-- tools box -->
                <div class="card-tools">
                    {{--  --}}
                </div>
                <!-- /. tools -->
              </div>
              <!-- /.card-header -->
                <form action="{{ URL::to('/article/'.$article->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="card-body pad">
                        <div class="form-group">
                          <label class="form-label">Title</label>
                          <input type="text" name="title" class="form-control" placeholder="Tuliskan title artikel" value="{{$article->title}}" required/>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Header</label>
                            <input type="text" name="header" class="form-control" placeholder="Tuliskan header tambahan"  value="{{$article->header}}" required/>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Image Upload</label>
                            <input type="file" name="image" class="form-control" name="image" >
                            <img src="{{ asset('images/artikel/'.$article->image_url) }}">
                        </div>
                        <div class="my-3">
                            <label class="form-label">Body</label>
                            <textarea name="body" class="textarea" placeholder="Place some text here"
                            style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{html_entity_decode($article->body)}}</textarea>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Footer</label>
                            <input type="text" name="footer" class="form-control" placeholder="Tuliskan footer tambahan" value="{{$article->footer}}" required/>
                        </div>
                        <div class="form-group row">
                          <div class="col">
                            <label class="form-label">Tag</label>
                            <input type="text" name="tag" class="form-control" placeholder="Tuliskan topik yang berkaitan dengan hal ini (ex: kerja, menarik, fulltime, tips) ..." value="{{$article->tag}}"  required/>
                          </div>
                        </div>
                        <p class="text-sm mb-0">
                            Editor <a href="https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg">Documentation and license
                            information.</a>
                        </p>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary w-100">Simpan Artikel</button>
                    </div>
                </form>
            </div>
          </div>
          <!-- /.col-->
        </div>
        <!-- ./row -->
      </section>
</div>
@endsection
@section('script')
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<script>
  $(function () {
    $('.textarea').summernote()
  })
</script>
@endsection

resources/views/article/index.blade.php
@extends('layout')
@section('dataTablesCSS')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection
@section('title') 
  Artikel
@endsection
@section('content')

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Artikel</h3>
                <div class="card-tools">
                  <a href="{{ url('admin/artikel/create') }}" class="btn btn-tool">
                      <i class="fa fa-plus"></i>
                      &nbsp; Tambah Data Baru
                  </a>
              </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Title</th>
                    <th>Tags</th>
                    <th>Writer</th>
                    <th>Aksi</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($articles as $article)
                    <tr>
                      <td>{{ $article->title }}</td>
                        <td>
                            @foreach (explode(',', $article->tag) as $tag)
                              <span class="m-1 badge bg-primary">{{ $tag }}</span>
                            @endforeach
                        </td>
                      <td>{{ $article->writer }}</td>

                      <td class="text-center">
                        <form method="POST" action="{{route('article.destroy', $article->id)}}">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE" />
                            <div class="btn-group">
                                <a class="btn btn-info" href="{{ url('article/read') .$article->id}}" title="lihat Data"><i class="fa fa-eye"></i></a>
                                <a class="btn btn-success" href="{{ route('article.edit', $article->id)}}" title="Ubah Data"><i class="fa fa-magic" aria-hidden="true"></i></a>
                                <button class="btn btn-danger" href="{{route('article.destroy', $article->id)}}"><i class="fa fa-trash"></i></button>

                            </div>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>Title</th>
                    <th>Tags</th>
                    <th>Writer</th>
                    <th>Aksi</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection
@section('dataTablesScript')
    <!-- DataTables -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
@endsection
@section('script')
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  <!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('./plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('./plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

</head>

<!-- AdminLTE -->
<script src="{{ asset('./dist/js/adminlte.js') }}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('./dist/js/demo.js') }}"></script>
<script src="{{ asset('./dist/js/pages/dashboard3.js') }}"></script>
@endsection

resources/views/article/read.blade.php
@extends('layout')
@section('title')
  artikel
@endsection
@section('content')
<div class="container isidetailClbk">
<br><br><br><br>


  <div class="row">
    <div class="col p-3">
      @foreach ($articles as $article)
      <h1 class="fw-500">{{ $article->title }}</h1>
      <h5>Penulis: <span>{{ $article->writer }} | {{ $article->created_at }}</span></h5>
    </div>
  </div>
  <div class="row-gambar-detailClbk">
    <div class="row mx-1">
      <p>
        {{ $article->header }}
      </p>
    </div>
    
    <div class="col">
      <p>
        <img src="{{ asset('images/artikel/'.$article->image_url) }}">
        @php
          $body = html_entity_decode($article->body);
        @endphp
        {!! $body !!}
      </p>

      <div class="row mx-1">
        <p>
          {{ $article->footer }}
        </p>
      </div>
      <div style="clear:both;"></div>
        @endforeach
      <div class="row">
        <div class="col">
          <h6>Baca juga : <a href=""></a></h6>
          <h6>Baca berikutnya</h6>
          <a href=""></a>
          <button type="button" class="btn btn-light my-3 text-success"><i class="fas fa-thumbs-up"></i> Suka</button>
          <h6>Komentar</h6>
        </div>
      </div>
    </div>
  </div>
   
</div>
@endsection

resources/views/dashboard.blade.php
@extends('layout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>
                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    You are Logged In
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Artikel</h3>
                <div class="card-tools">
                  <a href="{{ url('article/create') }}" class="btn btn-tool">
                      <i class="fa fa-plus"></i>
                      &nbsp; Tambah Data Baru
                  </a>
              </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Title</th>
                    <th>Tags</th>
                    <th>Writer</th>
                    <th>Aksi</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($articles as $article)
                    <tr>
                      <td>{{ $article->title }}</td>
                        <td>
                            @foreach (explode(',', $article->tag) as $tag)
                              <span class="m-1 badge bg-primary">{{ $tag }}</span>
                            @endforeach
                        </td>
                      <td>{{ $article->writer }}</td>

                      <td class="text-center">
                        <form method="POST" action="{{route('article.destroy', $article->id)}}">
                            @csrf
                            
                            <input type="hidden" name="_method" value="DELETE" />
                            <div class="btn-group">
                                <a class="btn btn-info" href="{{ url('article/read') .$article->id}}" title="lihat Data"><i class="fa fa-eye"></i></a>
                                <a class="btn btn-success" href="{{ route('article.edit', $article->id)}}" title="Ubah Data"><i class="fa fa-magic" aria-hidden="true"></i></a>
                                <button class="btn btn-danger" href="{{route('article.destroy', $article->id)}}"><i class="fa fa-trash"></i></button>
                            </div>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>Title</th>
                    <th>Tags</th>
                    <th>Writer</th>
                    <th>Aksi</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

@endsection
@section('dataTablesScript')
    <!-- DataTables -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
@endsection
@section('script')
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  <!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('./plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('./plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

</head>

@yield('dataTablesScript')
<!-- AdminLTE -->
<script src="{{ asset('./dist/js/adminlte.js') }}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('./dist/js/demo.js') }}"></script>
<script src="{{ asset('./dist/js/pages/dashboard3.js') }}"></script>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel - supri wahyu edi nugroho</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <style type="text/css">
        @import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600);
        body{
            margin: 0;
            font-size: .9rem;
            font-weight: 400;
            line-height: 1.6;
            color: #212529;
            text-align: left;
            background-color: #f5f8fa;
        }
        .navbar-laravel
        {
            box-shadow: 0 2px 4px rgba(0,0,0,.04);
        }
        .navbar-brand , .nav-link, .my-form, .login-form
        {
            font-family: Raleway, sans-serif;
        }
        .my-form
        {
            padding-top: 1.5rem;
            padding-bottom: 1.5rem;
        }
        .my-form .row
        {
            margin-left: 0;
            margin-right: 0;
        }
        .login-form
        {
            padding-top: 1.5rem;
            padding-bottom: 1.5rem;
        }
        .login-form .row
        {
            margin-left: 0;
            margin-right: 0;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ route('welcome') }}">Laravel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">Register</a>
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('logout') }}">Logout</a>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>
@yield('content')
</body>
</html>